/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.productoctl;

/**
 *
 * @author j
 */
public class EdicionProducto extends javax.swing.JPanel {
    private productoctl productoControl;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EdicionProducto.class.getName());

    /**
     * Creates new form EdicionProducto
     */
    public EdicionProducto(modelo.basededatos bd) {
        initComponents();
        this.productoControl = new productoctl(bd);
        cargarProductos();
    }
    
    
    private void cargarProductos() {
        jComboBoxProducto.removeAllItems();
        for (modelo.Producto p : productoControl.obtenerTodosProductos()) {
            jComboBoxProducto.addItem(p.getNombre());
        }
    }
    
    private void mostrarInfoProducto() {
        String productoNombre = (String) jComboBoxProducto.getSelectedItem();
        if (productoNombre != null && !productoNombre.isEmpty()) {
            modelo.Producto producto = productoControl.obtenerProducto(productoNombre, "nombre");
            if (producto != null) {
                producto_txt.setText(producto.getNombre());
                categoria_txt.setText(producto.getCategoria());
                cantidad.setText(Integer.toString(producto.getCantidad_total()));
                id_value.setText(producto.getId());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        categoria_txt = new javax.swing.JTextField();
        producto_txt = new javax.swing.JTextField();
        id_value = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        cantidad_label = new javax.swing.JLabel();
        categoria_label = new javax.swing.JLabel();
        producto_label = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Buscar producto:");

        jComboBoxProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxProducto.setForeground(new java.awt.Color(44, 62, 80));
        jComboBoxProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        jComboBoxProducto.setPreferredSize(new java.awt.Dimension(200, 36));
        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });

        categoria_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoria_txt.setForeground(new java.awt.Color(44, 62, 80));
        categoria_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        categoria_txt.setPreferredSize(new java.awt.Dimension(0, 36));

        producto_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        producto_txt.setForeground(new java.awt.Color(44, 62, 80));
        producto_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        producto_txt.setPreferredSize(new java.awt.Dimension(0, 36));
        producto_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto_txtActionPerformed(evt);
            }
        });

        id_value.setEditable(false);
        id_value.setBackground(new java.awt.Color(245, 245, 245));
        id_value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_value.setForeground(new java.awt.Color(44, 62, 80));
        id_value.setText("---");
        id_value.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        id_value.setPreferredSize(new java.awt.Dimension(0, 36));

        id_label.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        id_label.setForeground(new java.awt.Color(96, 96, 96));
        id_label.setText("ID:");
        id_label.setPreferredSize(new java.awt.Dimension(120, 20));

        cantidad.setEditable(false);
        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad.setForeground(new java.awt.Color(44, 62, 80));
        cantidad.setText("---");
        cantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        cantidad.setPreferredSize(new java.awt.Dimension(0, 36));

        cantidad_label.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cantidad_label.setForeground(new java.awt.Color(96, 96, 96));
        cantidad_label.setText("Cantidad total:");
        cantidad_label.setPreferredSize(new java.awt.Dimension(120, 20));

        categoria_label.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        categoria_label.setForeground(new java.awt.Color(96, 96, 96));
        categoria_label.setText("Categoría:");
        categoria_label.setPreferredSize(new java.awt.Dimension(120, 20));

        producto_label.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        producto_label.setForeground(new java.awt.Color(96, 96, 96));
        producto_label.setText("Producto:");
        producto_label.setPreferredSize(new java.awt.Dimension(120, 20));

        guardar.setBackground(new java.awt.Color(0, 102, 255));
        guardar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setFocusPainted(false);
        guardar.setPreferredSize(new java.awt.Dimension(100, 36));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(127, 140, 143));
        jButton3.setText("Reestablecer");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(120, 36));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxProducto, 0, 279, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(producto_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(producto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(id_value, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(categoria_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(categoria_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cantidad_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(66, 66, 66)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(producto_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(producto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoria_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(categoria_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidad_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String id = id_label.getText().trim();
        String nuevoNombre = producto_txt.getText().trim();
        String nuevaCategoria = categoria_txt.getText().trim();
        
        
        if (id.isEmpty() || nuevoNombre.isEmpty() || nuevaCategoria.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                javax.swing.SwingUtilities.getWindowAncestor(this),
                "Por favor complete nombre y categoria", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String resultado = productoControl.editarProducto(id, nuevoNombre, nuevaCategoria);
        
        
        javax.swing.JOptionPane.showMessageDialog(
            javax.swing.SwingUtilities.getWindowAncestor(this),
            resultado,
            "Resultado",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        producto_txt.setText("");
        categoria_txt.setText("");
                cantidad.setText("---");
                id_value.setText("---");
        jComboBoxProducto.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        mostrarInfoProducto();
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void producto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_txtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidad_label;
    private javax.swing.JLabel categoria_label;
    private javax.swing.JTextField categoria_txt;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_value;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel producto_label;
    private javax.swing.JTextField producto_txt;
    // End of variables declaration//GEN-END:variables
}

