/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.productoctl;

/**
 *
 * @author j
 */
public class EdicionProducto extends javax.swing.JPanel {
    private productoctl productoControl;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EdicionProducto.class.getName());

    /**
     * Creates new form EdicionProducto
     */
    public EdicionProducto(modelo.basededatos bd) {
        initComponents();
        this.productoControl = new productoctl(bd);
        cargarProductos();
    }
    
    
    private void cargarProductos() {
        jComboBoxProducto.removeAllItems();
        for (modelo.Producto p : productoControl.obtenerTodosProductos()) {
            jComboBoxProducto.addItem(p.nombre);
        }
    }
    
    private void mostrarInfoProducto() {
        String productoNombre = (String) jComboBoxProducto.getSelectedItem();
        if (productoNombre != null && !productoNombre.isEmpty()) {
            modelo.Producto producto = productoControl.obtenerProducto(productoNombre, "nombre");
            if (producto != null) {
                producto_txt.setText(producto.nombre);
                categoria_txt.setText(producto.categoria);
                cantidad.setText(Integer.toString(producto.cantidad_total));
                id_value.setText(producto.id);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        producto_label = new javax.swing.JLabel();
        producto_txt = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        id_value = new javax.swing.JTextField();
        categoria_label = new javax.swing.JLabel();
        categoria_txt = new javax.swing.JTextField();
        cantidad_label = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();

        setBackground(new java.awt.Color(245, 245, 245));

        guardar.setBackground(new java.awt.Color(46, 125, 50));
        guardar.setFont(new java.awt.Font("Segoe UI", 1, 13));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setFocusPainted(false);
        guardar.setPreferredSize(new java.awt.Dimension(100, 36));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13));
        jButton3.setForeground(new java.awt.Color(127, 140, 141));
        jButton3.setText("Reestablecer");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(120, 36));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Buscar producto:");

        jComboBoxProducto.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxProducto.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jComboBoxProducto.setForeground(new java.awt.Color(44, 62, 80));
        jComboBoxProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        jComboBoxProducto.setPreferredSize(new java.awt.Dimension(200, 36));
        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));

        producto_label.setFont(new java.awt.Font("Segoe UI", 0, 13));
        producto_label.setForeground(new java.awt.Color(96, 96, 96));
        producto_label.setText("Producto:");
        producto_label.setPreferredSize(new java.awt.Dimension(120, 20));

        categoria_label.setFont(new java.awt.Font("Segoe UI", 0, 13));
        categoria_label.setForeground(new java.awt.Color(96, 96, 96));
        categoria_label.setText("Categoría:");
        categoria_label.setPreferredSize(new java.awt.Dimension(120, 20));

        cantidad_label.setFont(new java.awt.Font("Segoe UI", 0, 13));
        cantidad_label.setForeground(new java.awt.Color(96, 96, 96));
        cantidad_label.setText("Cantidad total:");
        cantidad_label.setPreferredSize(new java.awt.Dimension(120, 20));

        id_label.setFont(new java.awt.Font("Segoe UI", 0, 13));
        id_label.setForeground(new java.awt.Color(96, 96, 96));
        id_label.setText("ID:");
        id_label.setPreferredSize(new java.awt.Dimension(120, 20));

        id_value.setEditable(false);
        id_value.setBackground(new java.awt.Color(245, 245, 245));
        id_value.setFont(new java.awt.Font("Segoe UI", 0, 14));
        id_value.setForeground(new java.awt.Color(44, 62, 80));
        id_value.setText("---");
        id_value.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        id_value.setPreferredSize(new java.awt.Dimension(0, 36));

        cantidad.setEditable(false);
        cantidad.setBackground(new java.awt.Color(245, 245, 245));
        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14));
        cantidad.setForeground(new java.awt.Color(44, 62, 80));
        cantidad.setText("---");
        cantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        cantidad.setPreferredSize(new java.awt.Dimension(0, 36));

        producto_txt.setBackground(new java.awt.Color(255, 255, 255));
        producto_txt.setFont(new java.awt.Font("Segoe UI", 0, 14));
        producto_txt.setForeground(new java.awt.Color(44, 62, 80));
        producto_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        producto_txt.setPreferredSize(new java.awt.Dimension(0, 36));
        producto_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto_txtActionPerformed(evt);
            }
        });

        categoria_txt.setBackground(new java.awt.Color(255, 255, 255));
        categoria_txt.setFont(new java.awt.Font("Segoe UI", 0, 14));
        categoria_txt.setForeground(new java.awt.Color(44, 62, 80));
        categoria_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        categoria_txt.setPreferredSize(new java.awt.Dimension(0, 36));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(id_value, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(producto_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(producto_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categoria_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(categoria_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cantidad_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_value))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoria_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String id = id_label.getText().trim();
        String nuevoNombre = producto_txt.getText().trim();
        String nuevaCategoria = categoria_txt.getText().trim();
        
        
        if (id.isEmpty() || nuevoNombre.isEmpty() || nuevaCategoria.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                javax.swing.SwingUtilities.getWindowAncestor(this),
                "Por favor complete nombre y categoria", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String resultado = productoControl.editarProducto(id, nuevoNombre, nuevaCategoria);
        
        
        javax.swing.JOptionPane.showMessageDialog(
            javax.swing.SwingUtilities.getWindowAncestor(this),
            resultado,
            "Resultado",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        producto_txt.setText("");
        categoria_txt.setText("");
                cantidad.setText("---");
                id_value.setText("---");
        jComboBoxProducto.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        mostrarInfoProducto();
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void producto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_txtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidad_label;
    private javax.swing.JLabel categoria_label;
    private javax.swing.JTextField categoria_txt;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_value;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel producto_label;
    private javax.swing.JTextField producto_txt;
    // End of variables declaration//GEN-END:variables
}

