/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author davig
 */
public class panel extends javax.swing.JPanel {
    modelo.Producto producto;

    /**
     * Creates new form panel
     */
    public panel(modelo.Producto p) {
        initComponents();
                this.producto =p;

    }
    
    
    public void escribir_panel_mini(){
        producto_label.setText(producto.nombre);
        categoria_label.setText(producto.categoria);
        cantidad_label.setText(String.valueOf(producto.cantidad_total));
        id_label.setText(producto.id);
        
        area_entregas.append("  #  | Cantidad |   Ingreso    | Vencimiento\n");
        String String_entrega;
        for(modelo.Entrega e :producto.entregas){
            String_entrega= "";
            
            String_entrega =(+e.numero+"        "+e.cantidad_por_entrega+"           "+e.ingreso);
            if (e.vencimiento == null) {
                String_entrega = String_entrega+("\n");
            } else {
                String_entrega = String_entrega+("     "+e.vencimiento+"\n");
            }
            
            area_entregas.append(String_entrega);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        producto_panel = new javax.swing.JPanel();
        categoria_label = new javax.swing.JLabel();
        cantidad_label = new javax.swing.JLabel();
        producto_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        cantidad_label4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_entregas = new javax.swing.JTextArea();

        categoria_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoria_label.setForeground(producto_label.getForeground());
        categoria_label.setText("Categoria:");

        cantidad_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad_label.setForeground(producto_label.getForeground());
        cantidad_label.setText("Cantidad total:");

        producto_label.setBackground(new java.awt.Color(102, 0, 102));
        producto_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        producto_label.setForeground(new java.awt.Color(44, 62, 80));
        producto_label.setText("Producto");

        id_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_label.setForeground(producto_label.getForeground());
        id_label.setText("id");

        cantidad_label4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad_label4.setForeground(producto_label.getForeground());
        cantidad_label4.setText("Entregas:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        area_entregas.setEditable(false);
        area_entregas.setBackground(new java.awt.Color(255, 255, 255));
        area_entregas.setColumns(20);
        area_entregas.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        area_entregas.setForeground(new java.awt.Color(44, 62, 80));
        area_entregas.setRows(5);
        jScrollPane1.setViewportView(area_entregas);

        javax.swing.GroupLayout producto_panelLayout = new javax.swing.GroupLayout(producto_panel);
        producto_panel.setLayout(producto_panelLayout);
        producto_panelLayout.setHorizontalGroup(
            producto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto_panelLayout.createSequentialGroup()
                .addComponent(id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(categoria_label)
                .addGap(35, 35, 35))
            .addGroup(producto_panelLayout.createSequentialGroup()
                .addComponent(cantidad_label4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, producto_panelLayout.createSequentialGroup()
                .addGroup(producto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(producto_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, producto_panelLayout.createSequentialGroup()
                        .addComponent(producto_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidad_label)))
                .addContainerGap())
        );
        producto_panelLayout.setVerticalGroup(
            producto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, producto_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(producto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_label)
                    .addComponent(cantidad_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(producto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label)
                    .addComponent(categoria_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad_label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(producto_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(producto_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_entregas;
    private javax.swing.JLabel cantidad_label;
    private javax.swing.JLabel cantidad_label4;
    private javax.swing.JLabel categoria_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel producto_label;
    private javax.swing.JPanel producto_panel;
    // End of variables declaration//GEN-END:variables
}
